name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Install Dependencies
      run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          php artisan config:clear
     
    - name: Deploy via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
          username: ${{ secrets.CLOUDWAYS_USER }}
          server: ${{ secrets.CLOUDWAYS_HOST }}
          port: 22
          ssh_private_key: ${{ secrets.CLOUDWAYS_SSH_KEY }}
          local_path: "./*"
          remote_path: "/home/1517904.cloudwaysapps.com/vzjpmgyckw/public_html/"
          sftp_only: true
